# Generated by Django 2.1.7 on 2019-04-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='3d1badd8506345f08ba90b6710247209', max_length=1000)),
                ('owner', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='402c965cc4074bb79b82493c022be239', max_length=1000)),
                ('owner', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('owner', models.CharField(max_length=1000)),
                ('meant_for', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Keys',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='0a1e81567d23492bbba71a090507e72f', max_length=1000)),
                ('owner', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.File')),
            ],
            options={
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('userAlias', models.EmailField(blank=True, max_length=254)),
                ('friends', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
    ]
