FROM python:3.6

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    && apt-get install -y zlib\
    && apt-get install -y python3\
    && apt-get install -y fuse \
    && apt-get install -y libfuse-dev \
    && apt-get install -y python3-pip \
    && pip install --upgrade pip \
    && pip install fusepy

WORKDIR /tmp/src
COPY fuse_client /tmp/src

RUN pip install -r requirements.txt